In [112]:
import pandas as pd
import numpy as np
from IPython.display import display

In [113]:
file_path = r'C:\Users\serik\OneDrive\Рабочий стол\MLFINAL\OldCarPricePrediction\car_price.csv'
df = pd.read_csv(file_path)
display(df)

,Unnamed: 0,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,0,Jeep Compass 2.0 Longitude Option BSIV,10.03 Lakh,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1,Renault Duster RXZ Turbo CVT,12.83 Lakh,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,2,Toyota Camry 2.5 G,16.40 Lakh,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,3,Honda Jazz VX CVT,7.77 Lakh,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,4,Volkswagen Polo 1.2 MPI Highline,5.15 Lakh,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...,...,...
5507,5507,BMW X1 sDrive 20d xLine,28.90 Lakh,"45,000 kms",Diesel,Automatic,1st Owner,2018,2995 cc,7 Seats
5508,5508,BMW M Series M4 Coupe,64.90 Lakh,"29,000 kms",Petrol,Automatic,2nd Owner,2015,1968 cc,5 Seats
5509,5509,Jaguar XF 2.2 Litre Luxury,13.75 Lakh,"90,000 kms",Diesel,Automatic,2nd Owner,2013,2755 cc,5 Seats
5510,5510,BMW 7 Series 730Ld,29.90 Lakh,"79,000 kms",Diesel,Automatic,3rd Owner,2015,2967 cc,6 Seats
5511,5511,BMW 5 Series 520d M Sport,31.90 Lakh,"42,000 kms",Diesel,Automatic,2nd Owner,2017,1991 cc,5 Seats

In [114]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [115]:
df.isnull().sum()

unnamed:_0             0
car_name               0
car_prices_in_rupee    0
kms_driven             0
fuel_type              0
transmission           0
ownership              0
manufacture            0
engine                 0
seats                  0
dtype: int64

In [116]:
df.dtypes

unnamed:_0              int64
car_name               object
car_prices_in_rupee    object
kms_driven             object
fuel_type              object
transmission           object
ownership              object
manufacture             int64
engine                 object
seats                  object
dtype: object

In [117]:
for column in df:
    print("Column:", column)
    print(df[column].value_counts())
    print()

Column: unnamed:_0
0       1
3671    1
3679    1
3678    1
3677    1
       ..
1836    1
1835    1
1834    1
1833    1
5511    1
Name: unnamed:_0, Length: 5512, dtype: int64

Column: car_name
Maruti Alto 800 LXI          53
Maruti Swift VXI             46
Maruti Wagon R VXI BS IV     43
Maruti Swift Dzire VDI       42
Maruti Swift Dzire VXI       42
                             ..
Tata New Safari XT            1
Hyundai Creta 1.6 E Plus      1
Toyota Etios 2014-2016 GD     1
Mahindra Marazzo M8 8Str      1
BMW M Series M4 Coupe         1
Name: car_name, Length: 1896, dtype: int64

Column: car_prices_in_rupee
4.50 Lakh     62
3.50 Lakh     62
3 Lakh        58
6.50 Lakh     57
5.50 Lakh     52
              ..
12.03 Lakh     1
15.62 Lakh     1
7.92 Lakh      1
29.25 Lakh     1
31.90 Lakh     1
Name: car_prices_in_rupee, Length: 1300, dtype: int64

Column: kms_driven
80,000 kms      163
1,20,000 kms    146
60,000 kms      142
50,000 kms      136
70,000 kms      132
               ...
79,385 kms        1
51,242 kms        1
38,733 kms        1
77,385 kms        1
85,002 kms        1
Name: kms_driven, Length: 2610, dtype: int64

Column: fuel_type
Petrol      2967
Diesel      2423
Cng           80
Lpg           28
Electric      14
Name: fuel_type, dtype: int64

Column: transmission
Manual       3962
Automatic    1550
Name: transmission, dtype: int64

Column: ownership
1st Owner    3736
2nd Owner    1314
3rd Owner     359
4th Owner      84
5th Owner      12
0th Owner       7
Name: ownership, dtype: int64

Column: manufacture
2017    621
2015    530
2018    526
2019    493
2016    470
2014    461
2013    372
2020    347
2021    344
2012    301
2011    263
2010    217
2022    145
2009    132
2008    113
2007     60
2006     42
2005     28
2004     16
2002     13
2003      8
2000      4
1998      2
2001      2
1995      1
1999      1
Name: manufacture, dtype: int64

Column: engine
1197 cc    714
1248 cc    395
998 cc     346
1498 cc    252
1497 cc    245
          ...
1173 cc      1
2359 cc      1
5950 cc      1
3956 cc      1
2979 cc      1
Name: engine, Length: 139, dtype: int64

Column: seats
5 Seats    4673
7 Seats     631
4 Seats      88
6 Seats      61
8 Seats      54
2 Seats       5
Name: seats, dtype: int64

In [118]:
import re
pattern = r"(\d+\.?\d*)"

In [119]:
df["car_prices_in_rupee"] = df["car_prices_in_rupee"].str.extract(pattern)
df["car_prices_in_rupee"] = pd.to_numeric(df["car_prices_in_rupee"], errors="coerce")
df["car_prices_in_rupee"].isna().sum()

0

In [120]:
df['kms_driven'] = df['kms_driven'].str.extract('(\d+,\d*)')
df['kms_driven'] = df['kms_driven'].str.replace(",", "")
df['kms_driven'] = pd.to_numeric(df['kms_driven'], errors='coerce')
df['kms_driven'] = df['kms_driven'].fillna(df['kms_driven'].mean())

In [123]:
df.isnull().sum()

unnamed:_0             0
car_name               0
car_prices_in_rupee    0
kms_driven             0
fuel_type              0
transmission           0
ownership              0
manufacture            0
engine                 0
seats                  0
dtype: int64

In [121]:
df["kms_driven"].isna().sum()

0

In [122]:
display(df)

,unnamed:_0,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,seats
0,0,Jeep Compass 2.0 Longitude Option BSIV,10.03,86226.0,Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1,Renault Duster RXZ Turbo CVT,12.83,13248.0,Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,2,Toyota Camry 2.5 G,16.40,60343.0,Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,3,Honda Jazz VX CVT,7.77,26696.0,Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,4,Volkswagen Polo 1.2 MPI Highline,5.15,69414.0,Petrol,Manual,1st Owner,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...,...,...
5507,5507,BMW X1 sDrive 20d xLine,28.90,45000.0,Diesel,Automatic,1st Owner,2018,2995 cc,7 Seats
5508,5508,BMW M Series M4 Coupe,64.90,29000.0,Petrol,Automatic,2nd Owner,2015,1968 cc,5 Seats
5509,5509,Jaguar XF 2.2 Litre Luxury,13.75,90000.0,Diesel,Automatic,2nd Owner,2013,2755 cc,5 Seats
5510,5510,BMW 7 Series 730Ld,29.90,79000.0,Diesel,Automatic,3rd Owner,2015,2967 cc,6 Seats
5511,5511,BMW 5 Series 520d M Sport,31.90,42000.0,Diesel,Automatic,2nd Owner,2017,1991 cc,5 Seats

In [57]:
df.dtypes

unnamed:_0               int64
car_name                object
car_prices_in_rupee    float64
kms_driven              object
fuel_type               object
transmission            object
ownership               object
manufacture              int64
engine                  object
seats                   object
dtype: object

In [126]:
df['manufacture'] = df['manufacture'].astype('object')

In [127]:
df.dtypes

unnamed:_0               int64
car_name                object
car_prices_in_rupee    float64
kms_driven             float64
fuel_type               object
transmission            object
ownership               object
manufacture             object
engine                  object
seats                   object
dtype: object

In [125]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()

In [128]:
df['kms_driven'] = scaler.fit_transform(df[['kms_driven']])

In [129]:
from sklearn.preprocessing import OrdinalEncoder
ordinal = OrdinalEncoder()

In [130]:
oe_features = ['car_name', 'fuel_type', 'transmission', 'ownership', 'manufacture','engine','seats']
for feature in oe_features:
    df[feature] = ordinal.fit_transform(df[[feature]])

In [131]:
X = df.drop(["unnamed:_0", "car_prices_in_rupee"], axis=1)
y = df["car_prices_in_rupee"]

In [132]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, shuffle=True, random_state=1)

In [133]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import LearningRateScheduler
from tensorflow.keras.losses import MeanSquaredError
from sklearn.metrics import mean_squared_error

In [134]:
def create_model(input_shape, dropout_rate=0.2, weight_decay=0.0001):
    model = Sequential()
    model.add(layers.InputLayer(input_shape=input_shape))
    model.add(layers.Dense(128, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(layers.Dropout(dropout_rate))
    model.add(layers.Dense(64, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(layers.Dropout(dropout_rate))
    model.add(layers.Dense(32, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(weight_decay)))
    model.add(layers.Dropout(dropout_rate))
    model.add(layers.Dense(1, activation='linear'))
    return model

In [135]:
def scheduler(epoch, lr):
    if epoch < 30:
        return lr
    else:
        return lr * 0.1

In [140]:
input_shape = X_train.shape[1]
model = create_model(input_shape)
model.compile(optimizer=Adam(learning_rate=0.001), loss=MeanSquaredError(), metrics=['mse'])

callbacks = [LearningRateScheduler(scheduler, verbose=1)]
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_val, y_val), callbacks=callbacks)

Epoch 1: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 1/50
138/138 [==============================] - 1s 2ms/step - loss: 834.1465 - mse: 834.1345 - val_loss: 272.3455 - val_mse: 272.3343 - lr: 0.0010

Epoch 2: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 2/50
138/138 [==============================] - 0s 2ms/step - loss: 343.7524 - mse: 343.7412 - val_loss: 274.2490 - val_mse: 274.2376 - lr: 0.0010

Epoch 3: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 3/50
138/138 [==============================] - 0s 1ms/step - loss: 307.3366 - mse: 307.3252 - val_loss: 259.1531 - val_mse: 259.1414 - lr: 0.0010

Epoch 4: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 4/50
138/138 [==============================] - 0s 1ms/step - loss: 284.5445 - mse: 284.5326 - val_loss: 267.5304 - val_mse: 267.5185 - lr: 0.0010

Epoch 5: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 5/50
138/138 [==============================] - 0s 2ms/step - loss: 284.5340 - mse: 284.5220 - val_loss: 254.7232 - val_mse: 254.7112 - lr: 0.0010

Epoch 6: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 6/50
138/138 [==============================] - 0s 2ms/step - loss: 279.7079 - mse: 279.6957 - val_loss: 258.2562 - val_mse: 258.2439 - lr: 0.0010

Epoch 7: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 7/50
138/138 [==============================] - 0s 1ms/step - loss: 274.6772 - mse: 274.6649 - val_loss: 261.1813 - val_mse: 261.1690 - lr: 0.0010

Epoch 8: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 8/50
138/138 [==============================] - 0s 1ms/step - loss: 276.4350 - mse: 276.4226 - val_loss: 257.7814 - val_mse: 257.7689 - lr: 0.0010

Epoch 9: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 9/50
138/138 [==============================] - 0s 1ms/step - loss: 273.8556 - mse: 273.8430 - val_loss: 243.8169 - val_mse: 243.8042 - lr: 0.0010

Epoch 10: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 10/50
138/138 [==============================] - 0s 2ms/step - loss: 273.2631 - mse: 273.2502 - val_loss: 251.0794 - val_mse: 251.0665 - lr: 0.0010

Epoch 11: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 11/50
138/138 [==============================] - 0s 2ms/step - loss: 270.7570 - mse: 270.7442 - val_loss: 245.5033 - val_mse: 245.4904 - lr: 0.0010

Epoch 12: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 12/50
138/138 [==============================] - 0s 2ms/step - loss: 272.5213 - mse: 272.5082 - val_loss: 249.4507 - val_mse: 249.4375 - lr: 0.0010

Epoch 13: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 13/50
138/138 [==============================] - 0s 1ms/step - loss: 263.8748 - mse: 263.8615 - val_loss: 242.1240 - val_mse: 242.1106 - lr: 0.0010

Epoch 14: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 14/50
138/138 [==============================] - 0s 1ms/step - loss: 269.0411 - mse: 269.0276 - val_loss: 244.8726 - val_mse: 244.8590 - lr: 0.0010

Epoch 15: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 15/50
138/138 [==============================] - 0s 1ms/step - loss: 266.1713 - mse: 266.1576 - val_loss: 246.7223 - val_mse: 246.7085 - lr: 0.0010

Epoch 16: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 16/50
138/138 [==============================] - 0s 1ms/step - loss: 266.6665 - mse: 266.6526 - val_loss: 253.8262 - val_mse: 253.8122 - lr: 0.0010

Epoch 17: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 17/50
138/138 [==============================] - 0s 2ms/step - loss: 267.9572 - mse: 267.9430 - val_loss: 246.2684 - val_mse: 246.2541 - lr: 0.0010

Epoch 18: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 18/50
138/138 [==============================] - 0s 2ms/step - loss: 264.8310 - mse: 264.8165 - val_loss: 244.8846 - val_mse: 244.8699 - lr: 0.0010

Epoch 19: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 19/50
138/138 [==============================] - 0s 2ms/step - loss: 262.7530 - mse: 262.7381 - val_loss: 238.1614 - val_mse: 238.1465 - lr: 0.0010

Epoch 20: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 20/50
138/138 [==============================] - 0s 1ms/step - loss: 267.1393 - mse: 267.1241 - val_loss: 252.7103 - val_mse: 252.6951 - lr: 0.0010

Epoch 21: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 21/50
138/138 [==============================] - 0s 1ms/step - loss: 265.1891 - mse: 265.1736 - val_loss: 250.0824 - val_mse: 250.0667 - lr: 0.0010

Epoch 22: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 22/50
138/138 [==============================] - 0s 1ms/step - loss: 265.3004 - mse: 265.2845 - val_loss: 237.0280 - val_mse: 237.0119 - lr: 0.0010

Epoch 23: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 23/50
138/138 [==============================] - 0s 1ms/step - loss: 259.7247 - mse: 259.7086 - val_loss: 242.4539 - val_mse: 242.4376 - lr: 0.0010

Epoch 24: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 24/50
138/138 [==============================] - 0s 1ms/step - loss: 263.3961 - mse: 263.3795 - val_loss: 239.5539 - val_mse: 239.5370 - lr: 0.0010

Epoch 25: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 25/50
138/138 [==============================] - 0s 1ms/step - loss: 264.6754 - mse: 264.6581 - val_loss: 239.2412 - val_mse: 239.2237 - lr: 0.0010

Epoch 26: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 26/50
138/138 [==============================] - 0s 1ms/step - loss: 262.6375 - mse: 262.6200 - val_loss: 240.0482 - val_mse: 240.0303 - lr: 0.0010

Epoch 27: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 27/50
138/138 [==============================] - 0s 1ms/step - loss: 263.4674 - mse: 263.4493 - val_loss: 237.1168 - val_mse: 237.0985 - lr: 0.0010

Epoch 28: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 28/50
138/138 [==============================] - 0s 1ms/step - loss: 262.6845 - mse: 262.6658 - val_loss: 247.1801 - val_mse: 247.1611 - lr: 0.0010

Epoch 29: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 29/50
138/138 [==============================] - 0s 1ms/step - loss: 260.1783 - mse: 260.1589 - val_loss: 240.9258 - val_mse: 240.9062 - lr: 0.0010

Epoch 30: LearningRateScheduler setting learning rate to 0.0010000000474974513.
Epoch 30/50
138/138 [==============================] - 0s 1ms/step - loss: 260.2485 - mse: 260.2285 - val_loss: 239.0809 - val_mse: 239.0606 - lr: 0.0010

Epoch 31: LearningRateScheduler setting learning rate to 0.00010000000474974513.
Epoch 31/50
138/138 [==============================] - 0s 1ms/step - loss: 256.1063 - mse: 256.0858 - val_loss: 236.2748 - val_mse: 236.2544 - lr: 1.0000e-04

Epoch 32: LearningRateScheduler setting learning rate to 1.0000000474974514e-05.
Epoch 32/50
138/138 [==============================] - 0s 1ms/step - loss: 256.1331 - mse: 256.1127 - val_loss: 236.5622 - val_mse: 236.5417 - lr: 1.0000e-05

Epoch 33: LearningRateScheduler setting learning rate to 1.0000000656873453e-06.
Epoch 33/50
138/138 [==============================] - 0s 1ms/step - loss: 257.4088 - mse: 257.3884 - val_loss: 236.5468 - val_mse: 236.5263 - lr: 1.0000e-06

Epoch 34: LearningRateScheduler setting learning rate to 1.0000001111620805e-07.
Epoch 34/50
138/138 [==============================] - 0s 1ms/step - loss: 257.2282 - mse: 257.2078 - val_loss: 236.5499 - val_mse: 236.5294 - lr: 1.0000e-07

Epoch 35: LearningRateScheduler setting learning rate to 1.000000082740371e-08.
Epoch 35/50
138/138 [==============================] - 0s 1ms/step - loss: 256.1987 - mse: 256.1782 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-08

Epoch 36: LearningRateScheduler setting learning rate to 1.000000082740371e-09.
Epoch 36/50
138/138 [==============================] - 0s 1ms/step - loss: 252.6704 - mse: 252.6499 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-09

Epoch 37: LearningRateScheduler setting learning rate to 1.000000082740371e-10.
Epoch 37/50
138/138 [==============================] - 0s 1ms/step - loss: 255.9955 - mse: 255.9751 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-10

Epoch 38: LearningRateScheduler setting learning rate to 1.000000082740371e-11.
Epoch 38/50
138/138 [==============================] - 0s 1ms/step - loss: 253.0261 - mse: 253.0057 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-11

Epoch 39: LearningRateScheduler setting learning rate to 1.000000082740371e-12.
Epoch 39/50
138/138 [==============================] - 0s 1ms/step - loss: 255.0293 - mse: 255.0088 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-12

Epoch 40: LearningRateScheduler setting learning rate to 1.0000001044244145e-13.
Epoch 40/50
138/138 [==============================] - 0s 1ms/step - loss: 256.8837 - mse: 256.8632 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-13

Epoch 41: LearningRateScheduler setting learning rate to 1.0000001179769417e-14.
Epoch 41/50
138/138 [==============================] - 0s 1ms/step - loss: 252.8210 - mse: 252.8004 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-14

Epoch 42: LearningRateScheduler setting learning rate to 1.0000001518582595e-15.
Epoch 42/50
138/138 [==============================] - 0s 1ms/step - loss: 259.5675 - mse: 259.5470 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-15

Epoch 43: LearningRateScheduler setting learning rate to 1.0000001095066122e-16.
Epoch 43/50
138/138 [==============================] - 0s 1ms/step - loss: 253.5474 - mse: 253.5267 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-16

Epoch 44: LearningRateScheduler setting learning rate to 1.0000000830368326e-17.
Epoch 44/50
138/138 [==============================] - 0s 1ms/step - loss: 252.1611 - mse: 252.1406 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-17

Epoch 45: LearningRateScheduler setting learning rate to 1.0000000664932204e-18.
Epoch 45/50
138/138 [==============================] - 0s 1ms/step - loss: 257.0541 - mse: 257.0336 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-18

Epoch 46: LearningRateScheduler setting learning rate to 1.000000045813705e-19.
Epoch 46/50
138/138 [==============================] - 0s 1ms/step - loss: 257.4805 - mse: 257.4601 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-19

Epoch 47: LearningRateScheduler setting learning rate to 1.000000032889008e-20.
Epoch 47/50
138/138 [==============================] - 0s 1ms/step - loss: 255.1133 - mse: 255.0928 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-20

Epoch 48: LearningRateScheduler setting learning rate to 1.0000000490448793e-21.
Epoch 48/50
138/138 [==============================] - 0s 1ms/step - loss: 253.6961 - mse: 253.6756 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-21

Epoch 49: LearningRateScheduler setting learning rate to 1.0000000692397185e-22.
Epoch 49/50
138/138 [==============================] - 0s 1ms/step - loss: 254.6012 - mse: 254.5807 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-22

Epoch 50: LearningRateScheduler setting learning rate to 1.0000000944832675e-23.
Epoch 50/50
138/138 [==============================] - 0s 1ms/step - loss: 259.0204 - mse: 258.9998 - val_loss: 236.5500 - val_mse: 236.5296 - lr: 1.0000e-23

In [138]:
import xgboost as xgb

In [141]:
model2 = xgb.XGBRegressor(random_state=1, learning_rate=0.001, max_depth=10, n_estimators=300)

In [142]:
model2.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.001, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=10, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=300, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=1, ...)

In [145]:
y_pred = model2.predict(X_val)
rmse = np.sqrt(mean_squared_error(y_val, y_pred))

print('Validation RMSE of XGboost model: ', rmse)

Validation RMSE of XGboost model:  16.514981309203186

In [149]:
y_val_pred = model.predict(X_val)

rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))
print("RMSE for the validation set:", rmse)

35/35 [==============================] - 0s 632us/step
RMSE for the validation set: 15.379518042521937